### ISSUE TITLE
How to use the custom two pictures, one left and one right, no other arguments, to get the disparity map?

### ISSUE THREAD

**Issue by boom-syndra** [youmi-zym/TemporalStereo#15]
I can not find a script that can get a disparity map on a pair of images as input, does it only support inferrence for a specific dataset, and does not support demo inferrence of any pair of images as th input?

**Comment by youmi-zym** [comment]
Hi,

Please refer to here https://github.com/youmi-zym/TemporalStereo?tab=readme-ov-file#-testing for inferencing on custom dataset.

Best, 
Youmin
