### ISSUE TITLE
Would you provide other way to download the KITTI processed data?

### ISSUE THREAD

**Issue by mickeykang16** [youmi-zym/TemporalStereo#7]
Thanks for the nice work!
I cannot make a Baidu account to download the KITTI dataset. 
Would you share the data in other path?

**Comment by youmi-zym** [comment]
Hi,

We're trying to upload the data to Google Drive, please refer to [here](https://github.com/youmi-zym/TemporalStereo#kitti-20122015). For a really big dataset, such as Kitti raw, it's not able to upload to Google Drive. Or maybe you can share a link and then I can upload it there.

Best,
Youmin

**Comment by mickeykang16** [comment]
Thanks for your reply.
I actually sent an email to 'youmin.zhang2@unibo.it' with my Onedrive cloud address.
Would you check the email?
Please let me know if I need to make a contact to another email.

**Comment by youmi-zym** [comment]
Hi,

Both TartanAir and KITTI datasets are uploaded and available now, please refer to https://github.com/youmi-zym/TemporalStereo#-datasets for more details.

Best,
Youmin
