### ISSUE TITLE
About the TartanAir dataset

### ISSUE THREAD

**Issue by killwy** [youmi-zym/TemporalStereo#8]
感谢您出色的工作! 关于TartanAir数据集上传的问题，您可以尝试以下两种解决方案：
1. 您可以尝试将数据集上传至opendatalab。具体操作可以参考文档（可能需要国内VPN才能打开）：https://openxlab.org.cn/docs/developers/%E6%95%B0%E6%8D%AE%E9%9B%86/%E6%95%B0%E6%8D%AE%E9%9B%86CLI%EF%BC%88%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%B7%A5%E5%85%B7%EF%BC%89.html
2. 您可以尝试将数据集分卷压缩，多传几个google drive的链接以避免单个文件占用空间过大。

**Comment by youmi-zym** [comment]
Hi,
 Thanks for the advices! We'll try. Thanks.

Best,
Youmin

**Comment by youmi-zym** [comment]
Hi,

Both TartanAir and KITTI datasets are uploaded and available now, please refer to https://github.com/youmi-zym/TemporalStereo#-datasets for more details.

Best,
Youmin

**Comment by killwy** [comment]
Thanks! Is the data used to train this model only a small fraction of the full tartanair dataset?
