### ISSUE TITLE
sceneflow tempoary mode

### ISSUE THREAD

**Issue by raoqiang** [youmi-zym/TemporalStereo#9]
thanks for release the great work, I found the sceneflow config frame idx=[0,], dose that means the sceneflow is only tested with single mode ?

**Comment by youmi-zym** [comment]
Hi,

Yes, exactly.

**Comment by raoqiang** [comment]
@youmi-zym is it because, on scenesflow, the accuracy temporal mode is not better than single mode?

**Comment by youmi-zym** [comment]
Hi,

The scene flow dataset provides few contiguous frames, and the view change between frames is quite big. Both properties are not suitable for video inference.

Best,
Youmin
